"""
Load sample data into the database.

This script loads the sample JSON data generated by generate_sample_data.py
into the PostgreSQL database.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
from datetime import datetime
from sqlalchemy.orm import Session
from backend.app.models.database import SessionLocal, init_db, init_postgis
from backend.app.models.tables import (
    Municipality, RoadSegment, Crash, CensusTract
)
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def load_municipalities(data_file: str, db: Session):
    """Load municipalities from JSON file."""
    logger.info("Loading municipalities...")

    with open(data_file, 'r') as f:
        municipalities = json.load(f)

    loaded_count = 0

    for muni_data in municipalities:
        # Check if already exists
        existing = db.query(Municipality).filter(
            Municipality.muni_code == muni_data['muni_code']
        ).first()

        if existing:
            logger.debug(f"Municipality {muni_data['name']} already exists, skipping")
            continue

        # Convert GeoJSON polygon to WKT
        coords = muni_data['boundary']['coordinates'][0]
        wkt_coords = ', '.join([f"{lon} {lat}" for lon, lat in coords])
        geom_wkt = f"SRID=4326;POLYGON(({wkt_coords}))"

        municipality = Municipality(
            name=muni_data['name'],
            county=muni_data['county'],
            muni_code=muni_data['muni_code'],
            geom=geom_wkt
        )

        db.add(municipality)
        loaded_count += 1

        if loaded_count % 10 == 0:
            db.commit()

    db.commit()
    logger.info(f"Loaded {loaded_count} municipalities")


def load_road_segments(data_file: str, db: Session):
    """Load road segments from JSON file."""
    logger.info("Loading road segments...")

    with open(data_file, 'r') as f:
        segments = json.load(f)

    loaded_count = 0

    for seg_data in segments:
        # Check if already exists
        existing = db.query(RoadSegment).filter(
            RoadSegment.osm_id == seg_data['osm_id']
        ).first()

        if existing:
            continue

        # Convert GeoJSON linestring to WKT
        coords = seg_data['geometry']['coordinates']
        wkt_coords = ', '.join([f"{lon} {lat}" for lon, lat in coords])
        geom_wkt = f"SRID=4326;LINESTRING({wkt_coords})"

        segment = RoadSegment(
            osm_id=seg_data['osm_id'],
            road_name=seg_data['road_name'],
            road_type=seg_data['road_type'],
            road_class=seg_data['road_class'],
            length_miles=seg_data['length_miles'],
            muni_id=seg_data['muni_id'],
            geom=geom_wkt
        )

        db.add(segment)
        loaded_count += 1

        if loaded_count % 100 == 0:
            db.commit()
            logger.info(f"Loaded {loaded_count} road segments...")

    db.commit()
    logger.info(f"Loaded {loaded_count} road segments")


def load_crashes(data_file: str, db: Session):
    """Load crashes from JSON file."""
    logger.info("Loading crashes...")

    with open(data_file, 'r') as f:
        crashes = json.load(f)

    loaded_count = 0

    for crash_data in crashes:
        # Check if already exists
        existing = db.query(Crash).filter(
            Crash.external_id == crash_data['external_id']
        ).first()

        if existing:
            continue

        # Convert to point WKT
        lon = crash_data['longitude']
        lat = crash_data['latitude']
        geom_wkt = f"SRID=4326;POINT({lon} {lat})"

        # Parse date
        crash_date = datetime.strptime(crash_data['crash_date'], '%Y-%m-%d').date()

        crash = Crash(
            external_id=crash_data['external_id'],
            crash_date=crash_date,
            crash_time=crash_data.get('crash_time'),
            severity=crash_data['severity'],
            ped_involved=crash_data['ped_involved'],
            bike_involved=crash_data['bike_involved'],
            muni_id=crash_data['muni_id'],
            road_name=crash_data.get('road_name'),
            geocode_quality=crash_data.get('geocode_quality', 'medium'),
            weather_condition=crash_data.get('weather_condition'),
            light_condition=crash_data.get('light_condition'),
            geom=geom_wkt
        )

        db.add(crash)
        loaded_count += 1

        if loaded_count % 500 == 0:
            db.commit()
            logger.info(f"Loaded {loaded_count} crashes...")

    db.commit()
    logger.info(f"Loaded {loaded_count} crashes")


def load_census_tracts(data_file: str, db: Session):
    """Load census tracts from JSON file."""
    logger.info("Loading census tracts...")

    with open(data_file, 'r') as f:
        tracts = json.load(f)

    loaded_count = 0

    for tract_data in tracts:
        # Check if already exists
        existing = db.query(CensusTract).filter(
            CensusTract.tract_id == tract_data['tract_id']
        ).first()

        if existing:
            continue

        # Convert GeoJSON polygon to WKT
        coords = tract_data['geometry']['coordinates'][0]
        wkt_coords = ', '.join([f"{lon} {lat}" for lon, lat in coords])
        geom_wkt = f"SRID=4326;POLYGON(({wkt_coords}))"

        tract = CensusTract(
            tract_id=tract_data['tract_id'],
            muni_id=tract_data.get('muni_id'),
            county_fips=tract_data.get('county_fips'),
            total_population=tract_data.get('total_population', 0),
            median_income=tract_data.get('median_income', 0),
            pct_below_poverty=tract_data.get('pct_below_poverty', 0),
            pct_no_vehicle=tract_data.get('pct_no_vehicle', 0),
            pct_minority=tract_data.get('pct_minority', 0),
            svi_score=tract_data.get('svi_score', 0),
            svi_percentile=tract_data.get('svi_percentile', 0),
            geom=geom_wkt
        )

        db.add(tract)
        loaded_count += 1

        if loaded_count % 50 == 0:
            db.commit()

    db.commit()
    logger.info(f"Loaded {loaded_count} census tracts")


def main():
    """Main data loading workflow."""
    logger.info("Starting sample data load...")

    # Check if data directory exists
    data_dir = "data/sample"
    if not os.path.exists(data_dir):
        logger.error(f"Sample data directory not found: {data_dir}")
        logger.info("Run generate_sample_data.py first to create sample data")
        sys.exit(1)

    # Initialize database
    logger.info("Initializing database...")
    try:
        init_postgis()
        logger.info("PostGIS extension enabled")
    except Exception as e:
        logger.warning(f"Could not enable PostGIS (may already be enabled): {e}")

    init_db()
    logger.info("Database schema created")

    # Create database session
    db = SessionLocal()

    try:
        # Load data in order (municipalities first, then data that references them)
        load_municipalities(f"{data_dir}/municipalities.json", db)
        load_road_segments(f"{data_dir}/road_segments.json", db)
        load_crashes(f"{data_dir}/crashes.json", db)
        load_census_tracts(f"{data_dir}/census_tracts.json", db)

        logger.info("\n" + "=" * 60)
        logger.info("✓ Sample data loaded successfully!")
        logger.info("=" * 60)

        # Show summary
        muni_count = db.query(Municipality).count()
        segment_count = db.query(RoadSegment).count()
        crash_count = db.query(Crash).count()
        tract_count = db.query(CensusTract).count()

        logger.info(f"\nDatabase contains:")
        logger.info(f"  - {muni_count} municipalities")
        logger.info(f"  - {segment_count} road segments")
        logger.info(f"  - {crash_count} crashes")
        logger.info(f"  - {tract_count} census tracts")

    except Exception as e:
        logger.error(f"Error loading data: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
